name: Deploy
on:
  workflow_run:
    workflows: [Lighthouse CI]
    types: [completed]
jobs:
  on-success:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: lighthouse.yml
          workflow_conclusion: success
          name: build-result
          path: ./dist
      - name: Deploy to release branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
